config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :planets do
    resources :bookings, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :find_planet , only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @planets = policy_scope(Planet)
    @i = @planets.count
  end

  def show
    @bookings = Booking.where(planet_id: params[:id])
  end

  def new
    @planet = Planet.new
    authorize @planet
  end
#TODO verifie create is working 
  def create
    @planet = Planet.new(planet_params)
    authorize @planet
    @planet.owner = current_user
    #@planet.owner = User.find(1)
    if @planet.save!
      redirect_to planet_path(@planet)
    else
      render :new
    end
  end
#TODO verifie create is working 
  def edit
  end

  def update
    if @planet.update!(planet_params)
      redirect_to planet_path(@planet), notice: 'This planet was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    if @planet.destroy
      redirect_to planets_path, notice: 'This planet was successfully deleted!'
    else
      redirect_to planet_path(@planet), notice: "Sorry, we need to reload our destroying machine..."
    end
  end

  private

  def find_planet
    @planet = Planet.find(params[:id])
    authorize @planet
  end
  def planet_params
    params.require(:planet).permit(:name , :description, :price, :photo)
  end
end

app/views/planets/edit.html.erb
<div class="container"style= "padding-top: 20vh;" >
<h1 style="color: white; font-weight: bold;">Planet editor</h1>
  <div class="card" >
  <%= simple_form_for(@planet) do |f| %>
  <%= f.input :name, as: :string, placeholder: @planet.name %>
  <%= f.input :description, as: :text, placeholder: @planet.description %>
  <%= f.input :price, as: :integer, placeholder: @planet.price %>
<div class="signup">
    <div class="growing">
      <%= f.button :submit, "Validé", class: 'btn btn-secondary' %>
    </div>
    <% end %>
      <%= link_to "Home", planets_path, class: 'btn btn-secondary' %>  
    </div>
  </div>
</div>

app/views/planets/index.html.erb
<div class="navbar">
  <div class="navbar-brand">
    <img id = "alien" src= <%= asset_path "alien.png"%>/>
  </div>
  <div class="navtext">
  <%= link_to 'Terra Booking', root_path, class: "terra-title" %>
    <%# <p class="terra-title">Terra Booking</p> %>
    <% unless user_signed_in? %>
      <%= link_to 'Log in', new_user_session_path, id: "Login"  %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% else %>
      <%= link_to 'Log out', destroy_user_session_path , method: :delete %>
    <% end %>
  </div>
</div>
  
<% @planets.reverse.each  do |planet|%>
  <% if @i == 1 %>
    <input checked='checked' class="planet<%="#{@i}"%>" id="<%="#{planet.name}"%>"name='planet' type='radio'>
  <% else %>
      <input class="planet<%="#{@i}"%>" id="<%="#{planet.name}"%>"name='planet' type='radio'>
  <% end %>
     <label class='menu' for="<%="#{planet.name}"%>">
      <h2>
      <div class='pip'></div>
      <%="#{planet.name}"%>
    </h2>
    <h3><%="#{planet.price} B$/year"%></h3>
    </label>
  <%@i -= 1 %>
<% end %>

<div class='solar'>
<% @planets.each_with_index  do |planet, index|%>
    <div class='solar_systm'>
    <div class="planet <%="#{planet.name}"%>">
    <div class="<%="planet_description #{planet.name}" %>">
        <h1><%= link_to "#{planet.name}",  planet_path(planet), class: 'white-btn'%></h1>
      <div style="background: linear-gradient(rgba(0,0,0,0) 0%, rgba(0,0,0,1) 50%,rgba(0,0,0,1)100%) , url('<%= img_planet(planet) %>'); position: absolute; width: 70rem; height: 50rem; left: -300px; top: -20px; border-radius: 100%; animation: translateBackground 45s infinite linear" >
      
      </div>
    <div class="clouds"></div>
      </div>
    </div>
  </div>
<% end %>
</div>
  <%= link_to 'Add a new planet', new_planet_path , class: "new_planet new-green-btn" %>




<!-- 
mercury = https://www.solarsystemscope.com/images/textures/full/2k_makemake_fictional.jpg

venus = https://nasa3d.arc.nasa.gov/shared_assets/images/ven0aaa2/ven0aaa2-copy-428-321.jpg

earth = https://img00.deviantart.net/04ef/i/2009/114/3/e/new_earth_texture_map_by_lightondesigns.jpg

mars = https://s3-us-west-2.amazonaws.com/s.cdpn.io/217233/mars_texture.jpg

jupiter = https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA07782_hires.jpg
saturne = https://www.solarsystemscope.com/images/textures/full/2k_saturn.jpg

uranus = https://img00.deviantart.net/957c/i/2017/165/4/9/uranus_texture_map_by_jcpag2010-db7yjwb.png

neptune = https://img00.deviantart.net/f068/i/2017/165/b/c/neptune_texture_map_by_jcpag2010-dbcjcv5.png

pluto = https://pre00.deviantart.net/4677/th/pre/f/2015/314/4/e/pluto_map__2015_nov_10__by_snowfall_the_cat-d918tlb.png
-->

app/views/planets/new.html.erb
<div class="container" style="padding-top: 20vh;">
<h1 style="color: white; font-weight: bold;">Add a new planet</h1>
<div class="card">
<%= simple_form_for(@planet) do |f| %>
  <%= f.input :name, as: :string %>
  <%= f.input :description, as: :text %>
  <%= f.input :price, as: :integer %>
  <%= f.input :photo, as: :file%>
<div class="signup">
    <div class="growing">
      <%= f.button :submit, "Add", class: 'btn btn-secondary' %>
    </div>
    <% end %>
      <%= link_to "Home", planets_path, class: 'btn btn-secondary' %>  
    </div>
  </div>
</div>

app/views/planets/show.html.erb
<div class="stars"></div>

<div class="planetoon"> 
  <div class="wrap">
     <div style="background-image: url('<%= img_planet(@planet) %>'); animation: translateBackground 40s infinite linear; width:300px; height:300px; position:absolute; border-radius:50%;" ></div>
     <div class="clouds"></div>   
  </div>
  <div class="mask"></div>
</div>


<div class="content-show">
  <div class="titree">
    <h1><%= @planet.name.upcase %> </h1>
    <h3><%= @planet.description %></h3>
    <h3><%="#{@planet.price} B$/year"%></h3>
  </div>

  <div class="content-bas">
  <% @years = 2020 %>
    <% @bookings.each do |booking| %> 
      <% @years += booking.duration.to_i %>
    <% end %>
    <h3><%= "You can book this planet from #{@years}" %></h3>
    <hr>

    <%= link_to planets_path do %>
      <%= image_tag "home.svg",class: 'abababa' %>
    <% end %>
    <% if @planet.owner != current_user && user_signed_in?%>
      <%= link_to new_planet_booking_path(@planet) do %>
      <%= image_tag "space.svg",class: 'abababa' %>
    <% end %>
  </div>      
    <% end %>
    <% if @planet.owner == current_user%>
    <%= link_to   edit_planet_path(@planet)do %>
        <%= image_tag "edit.svg" , class: 'abababa' %>
<% end %>

      <%= link_to   planet_path(@planet), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%= image_tag "trash.svg" , class: 'abababa2' %>
      <% end %>
<% end %>
</div>

 